textbook_index_terms = [u'seale', u'index', u'academic', u'freedom', u'access', u'board', u'us', u'centres',
                  u'accessforall', u'meta', u'data', u'specification', u'accessibility', u'standards',
                  u'learning', u'information', u'package', u'audit', u'auditor', u'awareness', u'benchmarks',
                  u'best', u'practice', u'business', u'case', u'law', u'committees', u'compliance', u'conformance',
                  u'consultants', u'definitions', u'enforcement', u'evaluation', u'guidelines', u'legislation',
                  u'markets', u'models', u'optimal', u'paradigm', u'cases', u'partial', u'policies', u'priority',
                  u'checkpoints', u'procurement', u'reasons', u'responsibility', u'rules', u'stakeholders', u'campus',
                  u'computers', u'disability', u'services', u'scale', u'environments', u'related', u'technologies',
                  u'alert', u'project', u'accessible', u'toolkit', u'accverify', u'activity', u'theory', u'adaptability',
                  u'administrative', u'model', u'alternative', u'augmentative', u'communication', u'aac', u'americans',
                  u'disabilities', u'act', u'prompt', u'art', u'design', u'arthritis', u'assessment', u'assistive',
                  u'technology', u'needs', u'devices', u'industry', u'office', u'outcomes', u'asthma', u'audio', u'audiomath',
                  u'barrier', u'free', u'blindness', u'bobby', u'braille', u'translation', u'software', u'browsers', u'captions',
                  u'captioning', u'magpie', u'charity', u'closed', u'circuit', u'television', u'cctv', u'code', u'memory',
                  u'diagram', u'animation', u'tool', u'cognitive', u'impairment', u'common', u'look', u'feel', u'communities',
                  u'laptop', u'networked', u'computer', u'laboratory', u'science', u'contextualized', u'courseware', u'virtual',
                  u'managed', u'management', u'systems', u'creative', u'authoring', u'tools', u'diabetes', u'dictaphone',
                  u'digital', u'collections', u'divide', u'advocates', u'training', u'attitudes', u'towards', u'declaration',
                  u'discrimination', u'rights', u'resource', u'australia', u'uk', u'codes', u'liaison', u'officer', u'dlo',
                  u'commission', u'education', u'distance', u'dyspraxia', u'dyslexia', u'easi', u'educational', u'developers',
                  u'communications', u'elearning', u'email', u'electronic', u'advisory', u'committee', u'reserves', u'engineering',
                  u'epilepsy', u'euroaccessibility', u'consortium', u'european', u'network', u'edean', u'automated', u'manual',
                  u'repair', u'reliability', u'validity', u'infocus', u'step', u'exclusion', u'filter', u'transformation',
                  u'flash', u'multimedia', u'head', u'mice', u'hearing', u'heart', u'attack', u'holistic', u'html', u'coding',
                  u'human', u'interaction', u'equal', u'opportunities', u'ims', u'global', u'inclusion', u'inclusive', u'individualized',
                  u'standard', u'ict', u'institutional', u'change', u'north', u'framework', u'international', u'classification',
                  u'function', u'icf', u'handicap', u'icdh', u'organization', u'iso', u'iterative', u'java', u'bridge', u'applets',
                  u'jaws', u'screen', u'reader', u'joint', u'keyboard', u'emulator', u'kurtzweil', u'system', u'object', u'resources',
                  u'technologists', u'lecturers', u'lecture', u'notes', u'librarians', u'library', u'catalogue', u'database',
                  u'professionals', u'support', u'web', u'site', u'environment', u'matching', u'persons', u'medical', u'mental',
                  u'health', u'mobile', u'national', u'centre', u'media', u'ncam', u'note', u'taking', u'machines', u'official',
                  u'civil', u'united', u'states', u'department', u'ocr', u'peer', u'mentors', u'tutoring', u'personal', u'assistant',
                  u'pda', u'phone', u'pdf', u'documents', u'personalization', u'physical', u'powerpoint', u'presentation',
                  u'applications', u'quality', u'indicators', u'qiat', u'rainbow', u'metaphor', u'reachability', u'remote',
                  u'experimentation', u'royal', u'institute', u'blind', u'rnib', u'supernova', u'magnification', u'zoomtext',
                  u'schizophrenia', u'section', u'rehabilitation', u'senior', u'managers', u'service', u'provision', u'simulations',
                  u'skill', u'skills', u'social', u'special', u'specialised', u'equipment', u'rooms', u'speech', u'synthesiser',
                  u'staff', u'development', u'online', u'courses', u'strategies', u'workshops', u'stroke', u'students', u'student',
                  u'centred', u'approach', u'switches', u'sydney', u'organising', u'olympic', u'games', u'socog', u'techdis',
                  u'federation', u'content', u'text', u'alternatives', u'graphics', u'word', u'trace', u'research', u'center',
                  u'transcriptions', u'ubiquitous', u'computing', u'universal', u'instructional', u'usability', u'user',
                  u'profiling', u'testing', u'video', u'webct', u'reality', u'visual', u'visually', u'impaired', u'voice',
                  u'recognition', u'voyager', u'mind', u'aim', u'initiative', u'wai', u'version', u'one', u'two', u'collaboration',
                  u'designers', u'mark', u'language', u'wireless', u'local', u'area', u'world', u'wide', u'w3c']
